### ISSUE TITLE
Auto RESET USB

### ISSUE THREAD

**Issue by custanator** [makermoekoe/ESP32Picoremote#2]
Hi! 
Thanks for posting a good project!
On Instagram, you wrote about the problem of automatic firmware management via USB
In your circuit, there are no resistors in a pair of transistors.
They are present in the official scheme of NodeMСU.
Maybe this is the problem?

![image](https://user-images.githubusercontent.com/5785354/116038810-9ae34400-a672-11eb-84c1-639fd2dd5b74.png)
![image](https://user-images.githubusercontent.com/5785354/116038827-a0d92500-a672-11eb-8cb4-ea3ef4fb2693.png)

**Comment by makermoekoe** [comment]
The BC847s is a dual npn transistor which will need two resistors for sure. The MUN5214DW1 has exactly the same pinout but it includes a simple bias resistor network. Therefore, the two resistors on the base are not necessary in this case. You can check the datasheet [here](https://www.onsemi.com/pdf/datasheet/dtc114yd-d.pdf).

The problem which I've mentioned on Instagram (which results in this huge pcb creature) was just a wrong capacitor value for the enable pin of the ESP32. It needs 10uF there.

**Comment by custanator** [comment]
All clear. Thank you!
